---
title: "Introduction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is the pop up project site for the work we are doing on marine species. 

Things you will need:

Tableau:

1. Download a copy of Tableau Desktop trial (you will need to sign up)
2. Download and open the workbook [here](https://github.com/poldham/asean_marine/raw/master/asean_literature.twbx) and open it. 

What you see is the scientific literature for the ASEAN region that contains a marine species. The list of species is ranked on the number of publications. If you click on a species name you will see some blue pop up hyperlinks. Those will take you to Google to look up the species, to patent searches and the scientific literature. The authors and organisations are also hyperlinked. 

Vantage Point Reader

You already have VP reader but it is [here](https://www.dropbox.com/s/ptbodjf9pt2qlgx/vp_reader_walkthru.mp4?dl=0) if you need it

The main files are here on Dropbox (as Github is not cooperating at the moment)

1. [wos_asean_marine](https://www.dropbox.com/s/z220sb7072bw954/wos_asean_marine_6659.vpt?dl=0)
2. [aseanlit_taxonomy](https://www.dropbox.com/s/pnf9uke1d7d8bl9/aseanlit_taxonomy.vpt?dl=0)
3. [Vantege point walkthrough](https://www.dropbox.com/s/ptbodjf9pt2qlgx/vp_reader_walkthru.mp4?dl=0) 
