---
title: "vibrio_harveyi"
author: "Nicola Shale"
date: "18/09/2017"
output: html_document
---

# Overview

**Species name:** *Vibrio harveyi*
**Kingdom:** Bacteria   
**Phylum:** Proteobacteria [GBIF](https://www.gbif.org/species/5427692)
  
**Brief Description of the Species:**  
[*Vibrio harveyi*](http://eol.org/pages/973242/details), is a Gram-negative, bioluminescent, common marine bacterium in the same genus as *Vibrio parahaemolyticus*. *V. harveyi* is rod-shaped and can be found free-swimming in tropical marine waters, living commensally in the gut microflora of marine animals, a minority of *V.harveyi* strains are pathogenic to marine animals, including Gorgonian corals, oysters, prawns, lobsters, the common snook, barramundi, turbot, milkfish, and seahorses. It is responsible for luminous vibriosis, a disease that affects commercially farmed penaeid prawns such as *P.monodon*. Additionally, based on samples taken by ocean-going ships, V. harveyi is thought to be the cause of the [milky seas effect] (https://www.nrl.navy.mil/media/news-releases/2005/nrl-scientists-detect-milky-sea-phenomena), in which, during the night, a uniform blue glow is emitted from the seawater. Some glows can cover nearly 6,000 sq mi (16,000 km2) (http://eol.org/pages/973242/details).

*V. harveyi* related strains have been isolated from the deep sea >1000m2, these may be ecologically differentiated strains, adapted to a different ecological niche or be distributed across the oceans (Thompson and Austin 2006). 

Although normally a benign bacteria in marine cultured environments, the prevalence of the pathogenic strains of *V. harveyi* - that differ by a few pathogenic determinant genes - can cause a problem in high nutrient, high density conditions leading to a rapid spread of virulent strains (Ben-Haim et al., 2003). 

Although closely related to the human pathogen *V. parahaemolyticus*, *V. harveyi* is not known as a [human pathogen](https://www.ncbi.nlm.nih.gov/genome?term=txid669%5Borgn%5D). This is one of the first organisms in which [quorum sensing] (https://www.ncbi.nlm.nih.gov/genome?term=txid669%5Borgn%5D) was described, whereby communities of bacteria communicate with each other via secreted signaling molecules synchronising community behaviour by regulating gene expression - both within and between bacteria species.  
  
**Known Distribution of the Species**  
Vibrio harveyi is a common bacteria inhabiting largely tropical marine waters - as it requires sodium chloride (10.1111/j.1472-765X.2006.01989.x), and prefers warmer water temperatures.
  
**First description**  
*Vibrio harveyi* was named by Baumann et al. in 1981, further to the work of Johnson & Shunk, 1936 who originally named the species *Achromobacter herveyi*. [GBIF](https://www.gbif.org/species/5427692) 

# Scientific Research on the Species  
  
**Research categories**  
Much of the research on *Vibrio harveyi* is categorised as Fisheries (72), Marine and Freshwater Biology (44), Veterinary Sciences (37),  Immunology (30), Microbiology (24), Biotechnology and Applied Microbiology (23) and Biochemistry and Molecular Biology (19).   
  
**Research summary**  
The research effort on *Vibrio harveyi* is largely concerned with infection of fish, molluscs and crustaceans within the aquaculture industry. As such a lot of the *V. harveyi* literature is concerned with understanding the pathogenic strains of the bacteria that infects commercially farmed marine organisms, partciularly shrimps: methods of rapidly detecting V.harveyi infections (2672.2003.02020.x), anitimicrobial peptides produced by marine organisms that could combat *V.harveyi* (10.1016/j.aquaculture.2009.01.026) and naturally occuring compunds that have antimicrobial properties against *V.harveyi* whilst being safe to cultured marine organisms(10.1111/are.13043). Shrimps infected with *V. harveyi* produce an antimcrobial peptide that has been shown to be effective in combatting the bacteria when administered into a culture or injected into shrimps(10.1016/j.aquaculture.2009.01.026).  

Overuse of antibiotics in aquaculture is blamed for an increase in antibiotic resistant strains of bacteria (10.1016/j.fm.2016.02.008), so *V.harveyi* researchers are looking at alternative methods of combatting the bacteria, including the use of novel natural compounds found in cyanobacteria(10.1111/are.13043) and extracts from *Sargassum oligocystum* (Apines-Amar, MJS. et al., 2011). 

**Aquatic or marine?**  
*Vibrio harveyi* is found in marine and estuarine waters, however its presence has also been noted in Giant Freshwater Prawn larvae which inhabit brackish water as juveniles and feshwater as adults(10.1016/j.aquaculture.2013.05.015).
  
**Is there a description of any research locations that you can identify?**  
Much of the research referencing specific locations for *V.harveyi* is from investigations into the cause of aquaculture shrimp mortalities as was the case in pond-cultured Penaeus monodon in the provinces of Bohol, Misamis Occidental, Lanao del Norte and Zamboanga del Sur, Philippines (Inui, Y. et al., 2003). Similarly dead shrimp larvae from hatcheries in Jepara, Indonesia(10.1016/0044-8486(94)00374-W), Southern Thailand (10.3354/dao035195), and Iran (Afsharnasab, M. et al., 2014) were found to contain *V.harveyi*. Seasonal changes in the composition of a variety of vibrio species including *V.harveyi* were investigated in samples taken from Yoshimi Bay, Hibiki-nada Sea, Japan.  
    
# Patent activity
  [Nucleic acid and amino acid sequences relating to pseudomonas aeruginosa for methods for the detection, prevention and treatment of pathological conditions resulting from bacterial infection including *V.harveyi*](https://www.lens.org/lens/patent/US_6551795_B1).
  
[Microorganisms for therapy wherein the microorganisms gather in inflamed or cancerous tissues and cause cells to become leaky, resulting in production of antibodies, one such type of microorganism is attentuated Vibrio](https://www.lens.org/lens/patent/US_2007_0212727_A1) 
  
[Lens collection](https://www.lens.org/lens/search?n=10&q=vibrio+harveyi&p=0&s=citing_pub_key_count&d=-#)
